navbar
frontend-park-mail-ru/2024_1_TeaStealers pull request #1
Opened 2024-02-22 21:49 UTC by FZTOtt

Добавил структуру каталогов. Добавил навигационную панель, инициализировал главные переменные.
PRI-19

2024-02-23 09:35 UTC, F4lkr4m commented
Наименовать PR'ты лучше тоже вразумительно, типа PRI-19: navbar

2024-02-23 09:51 UTC, F4lkr4m requested changes

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +.leftside {
Пустую строчку между стилями

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +.innernav {
тут скорее всего inner-nav, типа внутренняя навигация или просто класс nav

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    /* padding-left: 200px; */
Комменты стараемся оставлять только по делу, иначе код быстро становится весь в таких комментах

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +        <nav>
Вроде с тобой убирали лишний <nav>

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +    <header class="innernav">
https://ru.bem.info/methodology/solved-problems/ - давай попробуем сделать по бэму, как по ссылке

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +    <header class="innernav">
Тут будет class="nav"

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +            <div class="leftside">
Тут будет nav__leftside

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +                <ul class="linkbar">
Тут будет nav__linkbar

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +                <ul class="linkbar">
И так далее

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    position: relative;
Зачем явно указывать тут relative?

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    margin-right: auto;
Зачем margin-right: auto боксу, который находится справа?

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    min-width: 1024px;
Он разве не должен быть в приницпе во всю ширину?

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    position: relative;
Тоже тут relative не нужен

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    border-bottom: 1px solid gray;
точно, еще надо вынести в переменные цвета бордеров

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    color: white;
цвет текста не из переменной

2024-02-23 09:51 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +                <a href="" class="advert primary-button button-border-radius_sm">
Кстати, стоит разделять кнопку и ссылку. Лучше сделать кнопку в верстке через тег button. А потом просто ее обернуть в тег <a> по необходимости. Иначе так тебе придется делать две верстки кнопки: через тег <button> и через тег <a>.

2024-02-23 09:51 UTC, F4lkr4m commented on public/css/index.css
> +/* button-padding_md */
Тут тоже комменты - по необходимости

2024-02-23 16:16 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +.leftside {
fixed

2024-02-23 16:17 UTC, FZTOtt commented on public/components/navbar/navbar.html
> +        <nav>
то было другое, переделаю

2024-02-23 17:39 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +    margin-right: auto;
чтобы конпки были ближе к середине и не липли к краю страницы

2024-02-23 19:48 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +.innernav {
fixed

2024-02-23 19:49 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +    /* padding-left: 200px; */
fixed

2024-02-23 19:49 UTC, FZTOtt commented on public/components/navbar/navbar.html
> +        <nav>
fixed

2024-02-23 19:49 UTC, FZTOtt commented on public/components/navbar/navbar.html
> +    <header class="innernav">
fixed

2024-02-23 19:49 UTC, FZTOtt commented on public/components/navbar/navbar.html
> +            <div class="leftside">
fixed

2024-02-23 19:49 UTC, FZTOtt commented on public/components/navbar/navbar.html
> +                <ul class="linkbar">
fixed

2024-02-23 19:50 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +    position: relative;
fixed

2024-02-23 19:50 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +    min-width: 1024px;
fixed

2024-02-23 19:50 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +    position: relative;
fixed

2024-02-23 19:50 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +    border-bottom: 1px solid gray;
вынес, но не уверен в том что получилось, прошу присмотреться

2024-02-23 19:50 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +    color: white;
fixed

2024-02-24 05:31 UTC, FZTOtt commented on public/components/navbar/navbar.html
> +                <a href="" class="advert primary-button button-border-radius_sm">
fixed

2024-02-24 05:31 UTC, FZTOtt commented on public/css/index.css
> +/* button-padding_md */
fixed

2024-02-24 11:07 UTC, F4lkr4m requested changes

2024-02-24 11:07 UTC, F4lkr4m commented on README.md
> +# ForFrontPR
???

2024-02-24 11:07 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +    margin-right: auto;
А padding нельзя задать?

2024-02-24 11:07 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +.nav__rightside_secondary_button:hover {
button_secondary:hover*

2024-02-24 11:07 UTC, F4lkr4m commented on public/components/navbar/navbar.css
> +.nav__rightside_primary_button:hover {
primary_button:hover*

2024-02-24 11:07 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +                        <a href="https://qna.habr.com/q/230700">
ссылка на хабр сейчас не нужна

2024-02-24 14:25 UTC, FZTOtt commented on README.md
> +# ForFrontPR
поменял обратно, не знаю как так случилось)

2024-02-24 14:28 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +.nav__rightside_secondary_button:hover {
fixed

2024-02-24 14:29 UTC, FZTOtt commented on public/components/navbar/navbar.css
> +.nav__rightside_primary_button:hover {
fixed

2024-02-24 14:30 UTC, FZTOtt commented on public/components/navbar/navbar.html
> +                        <a href="https://qna.habr.com/q/230700">
fixed

2024-02-24 16:02 UTC, F4lkr4m approved these changes

2024-02-24 16:02 UTC, F4lkr4m commented on public/components/navbar/navbar.html
> +
Лишние пробельные строчки

2024-02-24 16:10 UTC, merged