PRI 45: scss and webpack
frontend-park-mail-ru/2024_1_TeaStealers pull request #20
Opened 2024-03-07 18:04 UTC by FZTOtt

Подключение к проекту препроцессора scss и webpack

PRI 45: scss and webpack

2024-03-10 19:19 UTC, F4lkr4m requested changes

2024-03-10 19:19 UTC, F4lkr4m commented on package.json
> +    "start": "npm run compile_scss && npm run compile_hbs && node server/index.js",
Должен быть запуск через вебпак, где поднимается сервер с hot reload

2024-03-10 19:19 UTC, F4lkr4m commented on package.json
> +    "start": "npm run compile_scss && npm run compile_hbs && node server/index.js",
При этом компилировать hbs и scss не нужно, это должен делать вебпак

2024-03-10 19:19 UTC, F4lkr4m commented on scss/button.scss
> +.button_primary {
Чтобы кучу раз button не писать можно сделать:
`.button {
  &_primary {}
  &_secondary {}
 // и так далее
}`

2024-03-10 19:19 UTC, F4lkr4m commented on scss/button.scss
> +.button_primary {
везде на такой формат переделать лучше

2024-03-10 19:19 UTC, F4lkr4m commented on scss/card.scss
> +.card__picture {
Используем вложенность scss &__picture

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +module.exports = {
Очень скромный конфиг, нет лоадеров, которые делают все необходимое

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +module.exports = {
Тут нехватает aliases - для того, чтобы можно было не использовать относительные импорты https://webpack.js.org/configuration/resolve/

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +module.exports = {
https://www.npmjs.com/package/handlebars-loader - лоадер hbs для вебпака

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
scss формат возьмет?)

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
https://webpack.js.org/loaders/sass-loader/

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +  },
Надо еще подрубить опцию девсервера для hot reload https://webpack.js.org/configuration/dev-server/

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +      { test: /\.svg$/, use: 'svg-inline-loader' },
Надо добавить file-loader на другую статику помимо  svg

2024-03-10 19:19 UTC, F4lkr4m commented on webpack.config.js
> +  },
https://www.npmjs.com/package/clean-webpack-plugin - еще подрубить этот плагин, чтобы он директорию с билдом чистил, иначе у тебя под конец семестра будет папка весом в 50гб со всеми билдами

2024-03-13 21:09 UTC, FZTOtt commented
лоадер на другую статику чуть позже

2024-03-13 21:10 UTC, FZTOtt commented on package.json
> +    "start": "npm run compile_scss && npm run compile_hbs && node server/index.js",
dev считается? или надо переписать?

2024-03-13 21:10 UTC, FZTOtt commented on scss/button.scss
> +.button_primary {
исправил

2024-03-13 21:10 UTC, FZTOtt commented on scss/card.scss
> +.card__picture {
исправил

2024-03-13 21:11 UTC, FZTOtt commented on webpack.config.js
> +module.exports = {
исправили, +добавил ещё алиасов

2024-03-13 21:11 UTC, FZTOtt commented on webpack.config.js
> +      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
исправили

2024-03-13 21:11 UTC, FZTOtt commented on webpack.config.js
> +  },
исправили

2024-03-16 13:19 UTC, F4lkr4m approved these changes

2024-03-16 13:19 UTC, F4lkr4m commented on package.json
> +    "fs": "^0.0.1-security",
Удалить это из зависимостей

2024-03-16 13:19 UTC, F4lkr4m commented on scss/index.scss
> +	background-color: #e2e5e7;
Здесь отступы странные

2024-03-16 13:19 UTC, F4lkr4m commented on scss/index.scss
> +		background-position: right -1 * $shine-width top 0;
И тут тоже странные

2024-03-16 13:19 UTC, F4lkr4m commented on scss/variables.scss
> +$color_basic: black;
По смыслу стоит пустыми строчками стили разделить

2024-03-18 07:11 UTC, merged