Pri 50: MVC and baseComponent
frontend-park-mail-ru/2024_1_TeaStealers pull request #23
Opened 2024-03-20 18:25 UTC by FZTOtt

Pri 50: MVC and baseComponent

2024-03-22 08:35 UTC, F4lkr4m requested changes

2024-03-22 08:35 UTC, F4lkr4m commented on public/components/navbar/navbar.js
>      if (codeStatus === 200) {
HTTP STATUS вынести

2024-03-22 08:35 UTC, F4lkr4m commented on public/components/search/search.js
> +    this.innerComponents[4].AddEventListener(click, listeners[click]);
4 - Magic Number
И что это за прикол вообще?

2024-03-22 08:35 UTC, F4lkr4m commented on public/index.html
> +    <!-- <link rel="stylesheet" href="./css/index.css"> -->
Удалить если не нужно

2024-03-22 08:35 UTC, F4lkr4m commented on public/index.js
> +// 404 500 400 403
Тут напоминание про HTTP STATUS константы

2024-03-22 08:35 UTC, F4lkr4m commented on public/index.js
> +let main;
Зачем тут определять main?

2024-03-22 08:35 UTC, F4lkr4m commented on public/models/mainModel.js
> +    if (statusCode !== 200) {
HTTP STATUS

2024-03-22 08:35 UTC, F4lkr4m commented on public/models/mainModel.js
> +async function getAdverts() {
Почему это находится за пределами модели?

2024-03-22 08:35 UTC, F4lkr4m commented on public/models/mainModel.js
> +let cardsData;
Почему это не часть модели?

2024-03-22 08:35 UTC, F4lkr4m commented on public/modules/router.js
> +
Лишняя строка

2024-03-22 08:35 UTC, F4lkr4m commented on public/modules/router.js
> +
Лишняя строка

2024-03-22 08:35 UTC, F4lkr4m commented on public/modules/router.js
> +        go(window.history.back())
А просто window.history.back() не сработает?

2024-03-22 08:35 UTC, F4lkr4m commented on public/views/mainView.js
> +  // BaseComponent
??

2024-03-22 08:35 UTC, F4lkr4m commented on public/views/mainView.js
> +//eventBus отслеживает у model, усть изменения - перерендер
Тут тоже комменты лишние

2024-03-28 19:27 UTC, F4lkr4m approved these changes

2024-03-28 19:27 UTC, F4lkr4m commented on package.json
> +    "compile_hbs": "globstar -- npx handlebars public/**/*.hbs -f public/templates/handlebars.precompiled.js",
Это можно убрать

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/baseComponent/baseComponent.js
> +export class BaseComponent {
JSDoc на класс потерял

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/baseComponent/baseComponent.js
> +        for (let key of Object.keys(this.state)) {
Почему не for (const key in this.state) ??

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/baseComponent/baseComponent.js
> +        for (let key of Object.keys(this.state)) {
Не забываем let/const

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/baseComponent/baseComponent.js
> +        if (state === undefined) {
Можно if (!state)

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/baseComponent/baseComponent.js
> +        // this.componentLink.addEventListener();
//

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/baseComponent/baseComponent.js
> +        this.innerComponents.forEach(component => component.componentWillUnmount());
лучше подключить правило в eslint, которое требует скобочки на callback функциях  https://eslint.org/docs/latest/rules/arrow-body-style

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/baseComponent/baseComponent.js
> +        this.innerComponents.forEach(component => component.componentWillUnmount());
Так будет более читаемо

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/gridCard/gridCard.js
> +  // render() {
//

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/loginForm/loginForm.js
> +// import { globalVariables } from '@models';
//

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/loginForm/loginForm.js
> +    // this.button.self.addEventListener('click', this.loginHandler.bind(this));
//

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/loginForm/loginForm.js
> +    this.innerComponents[2].self.addEventListener('click', this.loginHandler.bind(this));
Тут пошли MagicNumbers, давай как нибудь поменяем, типа const  LOGIN_BUTTON_INDEX = 2; - так хоть будет понятно, что на этом индексе находится кнопка. 

Но вообще еще лучше сделать для этого геттер или вынести функцию получения данного элемента типа this.getLoginButton().addEventListener(...) или this.loginButton.addEventListener(...)

А вообще еще мы знаем, что там есть id у кнопки и можно сделать просто document.confirmButton.addEventListener(...)

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/loginForm/loginForm.js
> +    const logValue = this.innerComponents[0].self.querySelector('input').value.trim();
Везде this.innerComponents[0] - где такая конструкция, мои комменты выше актуальны

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/loginForm/loginForm.js
> +      this.innerComponents[1].self.querySelector('input').removeEventListener('input', this.validatePasswordInput.bind(this));
Жесть тут мясо пошло, если такие конструкции получаются, то лучше делать переносы, чтобы было хоть читаемо:
```
this.innerComponents[1].self
    .querySelector('input')
    .removeEventListener('input', this.validatePasswordInput.bind(this));
```

Но советую тебе пересмотреть такую запись

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/loginForm/loginForm.js
> +    if (this.validateLoginInput !== undefined) {
if (this.validateLoginInput) ?

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/navbar/navbar.js
> +// import { globalVariables } from '@models';
//

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/navbar/navbar.js
> +    let innerComponents = [noticeButton, buttonLoginLogout];
let?

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/navbar/navbar.js
> +    let buttonLoginLogout = new Button('rightside', {
let?

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/navbar/navbar.js
>      if (codeStatus === 200) {
Да сделай же уже HTTP_STATUS

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/signupForm/signupForm.js
> +    this.innerComponents[0].self.querySelector('input').addEventListener('input', this.validateLoginInput.bind(this));
Тут у тебя массовое повторение кода идет, мб как-то это в функцию вынести?

2024-03-28 19:27 UTC, F4lkr4m commented on public/components/signupForm/signupForm.js
> +      this.innerComponents[1].self.querySelector('input').removeEventListener('input', this.validatePasswordInput.bind(this));
this.innerComponents[1] все те же комментарии

2024-03-29 19:42 UTC, FZTOtt commented on package.json
> +    "compile_hbs": "globstar -- npx handlebars public/**/*.hbs -f public/templates/handlebars.precompiled.js",
fix

2024-03-29 19:43 UTC, FZTOtt commented on public/components/baseComponent/baseComponent.js
> +export class BaseComponent {
fix

2024-03-29 19:43 UTC, FZTOtt commented on public/components/baseComponent/baseComponent.js
> +        for (let key of Object.keys(this.state)) {
fix

2024-03-29 19:44 UTC, FZTOtt commented on public/components/baseComponent/baseComponent.js
> +        if (state === undefined) {
fix

2024-03-29 20:22 UTC, FZTOtt commented on public/components/baseComponent/baseComponent.js
> +        this.innerComponents.forEach(component => component.componentWillUnmount());
added

2024-03-29 20:22 UTC, FZTOtt commented on public/components/baseComponent/baseComponent.js
> +        // this.componentLink.addEventListener();
delete

2024-03-29 20:23 UTC, FZTOtt commented on public/components/baseComponent/baseComponent.js
> +        for (let key of Object.keys(this.state)) {
eslint ругается на подобные конструкции. Заменил на
const statesAreEqual = Object.keys(this.state)
      .every((key) => { return this.state[key] === state[key]; });
    return statesAreEqual;

2024-03-30 17:42 UTC, merged