PRI 20: Search block
frontend-park-mail-ru/2024_1_TeaStealers pull request #3
Opened 2024-02-24 20:00 UTC by FZTOtt

Search block - блок с фоновой картинкой, приветственным сообщением и строкой поиска с фильтрами

PRI 20: Search block

2024-02-24 21:47 UTC, F4lkr4m requested changes

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +            <div class="search__block">
У тебя просто три блока вкладываются друг в друга, может объединить их стили. (я про search__area, search__main, search__block). Мы пытаемся делать верстку максимально простой - потом умрешь переписывать и делить это все

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                <div class="search__main_messedge">
search__main-message  main и message - это общее название блока, не модификатор

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                <div class="search__main_messedge">
Еще раз прочитай доку БЭМа https://ru.bem.info/methodology/quick-start/#модификатор

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                <div class="filter_and_search">
Если это единый компонент, то filter-and-search, а лучше search__filter-and-search

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +            <div class="search__block">
И также название классов не по БЭМ. Где у тебя основной блок? А где элемент? 
У тебя должен быть блок - search
А далее search__main-message
search__filter-and-search
search__string

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                        <li class="search__filter_link button_border-radius_md filter__active">
search__filter-link, не делаем больше одного элемента в классе, слишком длинный и не понятный получается

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                        <li class="search__filter_link button_border-radius_md filter__active">
filter_active - одно подчеркивание элемент_модификатор

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                        <li class="search__filter_link button_border-radius_md filter__passive">
тут все то же самое

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                    <div class="search_string button_border-radius_md">
search__string

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                        <button>
Без классов?

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                        <input type="text" placeholder="Город, адрес, метро, район" class="button_border-radius_md">
Почему у input классы кнопки? 
Должны быть отдельные классы для инпута
input_border-radius_md

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                <div class="search_button">
search__button

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +                        <li class="search__filter_link button_border-radius_md filter__active">
Что тут делают классы кнопки? Получается не по семантике

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.html
> +
Лишние пробелы не оставляем

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.css
> +
Лишние пробелы не оставляем

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.css
> +.search__main_messedge {
message*

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.css
> +.search__main_messedge {
search__main-message

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.css
> +.search_button button {
Почему абсолютное позиционирование?

2024-02-24 21:47 UTC, F4lkr4m commented on public/components/search/search.css
> +.search_button button {
Относительное > абсолютное

2024-02-25 18:19 UTC, FZTOtt commented on public/components/search/search.html
> +            <div class="search__block">
fixed

2024-02-25 18:19 UTC, FZTOtt commented on public/components/search/search.html
> +                <div class="search__main_messedge">
fixed

2024-02-25 18:20 UTC, FZTOtt commented on public/components/search/search.html
> +                <div class="filter_and_search">
fixed

2024-02-25 18:20 UTC, FZTOtt commented on public/components/search/search.html
> +                        <li class="search__filter_link button_border-radius_md filter__active">
fixed

2024-02-25 18:21 UTC, FZTOtt commented on public/components/search/search.html
> +                        <li class="search__filter_link button_border-radius_md filter__passive">
fixed

2024-02-25 18:21 UTC, FZTOtt commented on public/components/search/search.html
> +                    <div class="search_string button_border-radius_md">
fixed

2024-02-25 18:28 UTC, FZTOtt commented on public/components/search/search.html
> +                        <input type="text" placeholder="Город, адрес, метро, район" class="button_border-radius_md">
fixed

2024-02-25 18:28 UTC, FZTOtt commented on public/components/search/search.html
> +                        <button>
fixed

2024-02-25 18:28 UTC, FZTOtt commented on public/components/search/search.html
> +                <div class="search_button">
fixed

2024-02-25 18:28 UTC, FZTOtt commented on public/components/search/search.html
> +
fixed

2024-02-25 18:29 UTC, FZTOtt commented on public/components/search/search.css
> +
fixed

2024-02-25 18:29 UTC, FZTOtt commented on public/components/search/search.css
> +.search__main_messedge {
fixed

2024-02-25 18:30 UTC, FZTOtt commented on public/components/search/search.css
> +.search_button button {
fixed

2024-02-25 20:54 UTC, F4lkr4m approved these changes

2024-02-25 20:54 UTC, F4lkr4m commented on public/components/search/search.html
> +                    <button class="string_button">
Что значит string button?

2024-02-25 20:54 UTC, F4lkr4m commented on public/components/search/search.html
> +                    <input type="text" placeholder="Город, адрес, метро, район" class="string_input input_border-radius_md">
search__input

2024-02-26 17:35 UTC, FZTOtt commented on public/components/search/search.html
> +                    <button class="string_button">
fixed

2024-02-26 17:35 UTC, FZTOtt commented on public/components/search/search.html
> +                    <input type="text" placeholder="Город, адрес, метро, район" class="string_input input_border-radius_md">
fixed

2024-02-26 17:45 UTC, merged