Pri-14: login and sign up pages
frontend-park-mail-ru/2024_1_TeaStealers pull request #4
Opened 2024-02-24 22:48 UTC by marrgancovka

2024-02-25 10:45 UTC, F4lkr4m requested changes
Помимо вышесказанных замечаний, у тебя тут идет дублирование стилей для обоих форм. Можно создать какой-то общий css файл и назвать его, например, loginSignup.css и туда вынести общие стили, чтобы не дублировать

2024-02-25 10:45 UTC, F4lkr4m commented on public/css/index.css
> +    --color_highlight: #0468FF;
highlight для чего?

2024-02-25 10:45 UTC, F4lkr4m commented on public/css/index.css
> +    --color_basic: #152242;
basic для чего?

2024-02-25 10:45 UTC, F4lkr4m commented on public/css/index.css
> +input{
после селектора пробел `input {`

2024-02-25 10:45 UTC, F4lkr4m commented on public/css/index.css
> +input{
И также в других css файлах

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/login/login.html
> +            <div class="modal__content__btn-close">
modal__close-button

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/login/login.html
> +            <div class="modal__content__btn-close">
Пытаемся сохранить читабельность, также чтобы селектор не был слишком длинный. У тебя получается блок_элемент - блок - modal, элемент close-button

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/login/login.html
> +            <div class="modal__content__btn-close">
Также ниже по списку
modal__content__title
modal__content__input
modal__content__btn
modal__content__link

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/login/login.html
> +                <span class="error_message">Пример ошибки</span>
если это универсальный класс и к БЭМ он не относится то стоит его указывать как единое именование error-message

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/login/login.css
> +    font-size: var(--button-font-size);
Почему в модалке используются переменные для кнопки? Это должны быть либо универсальные переменные типа просто font-size, либо modal-font-size

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/login/login.html
> +            <button class="modal__content__btn">Войти</button>
Антон создавал стили для кнопок - они лежат в navbar - их можно вынести в index.css и использовать как общие и переиспользовать у себя

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/login/login.html
> +            <span class="error_message error_message_mg0">Пример ошибки с бэкенда</span>
Что такое error_message_mg0?

2024-02-25 10:45 UTC, F4lkr4m commented on public/pages/signup/signup.html
> +                <input type="text" placeholder="Логин" class="input">
Зачем тебе на input'ах  `class="input"`, если ты задала стили для всех input'ов с тегом  `<input>`

2024-02-25 14:39 UTC, mars444 commented on public/css/index.css
> +    --color_basic: #152242;
text-basic мб?
или это (background) bg-basic?
добавбте в название блок, для которого он будет использоваться

2024-02-25 14:40 UTC, mars444 commented on public/pages/login/login.css
> +    font-size: var(--button-font-size);
это классы для кнопки модалки, вроде норм

2024-02-25 21:41 UTC, marrgancovka commented on public/css/index.css
> +    --color_highlight: #0468FF;
исправила

2024-02-26 09:23 UTC, marrgancovka commented on public/css/index.css
> +    --color_highlight: #0468FF;
text, исправила

2024-02-26 09:24 UTC, marrgancovka commented on public/pages/login/login.css
> +    font-size: var(--button-font-size);
этот класс вообще убрала. теперь используются стили для кнопок из index.css

2024-02-26 09:25 UTC, marrgancovka commented on public/pages/login/login.html
> +            <span class="error_message error_message_mg0">Пример ошибки с бэкенда</span>
убрала

2024-02-26 09:25 UTC, marrgancovka commented on public/pages/signup/signup.html
> +                <input type="text" placeholder="Логин" class="input">
убрала

2024-02-26 19:59 UTC, F4lkr4m approved these changes

2024-02-26 19:59 UTC, F4lkr4m commented on public/pages/login/loginSignup.css
считаю надо сделать папку loginAndSignup и в ней:
loginAndSignup/loginAndSignup.css
loginAndSignup/login/login.html
loginAndSignup/signup/signup.html

2024-02-26 20:01 UTC, F4lkr4m commented
сделай git rebase на dev ветку, чтобы убрать конфликты
потом надо соединить все в один коммит, для этого:
git reset HEAD~(количество_коммитов, которые надо соединить)    // пример - git reset HEAD~2
git add .
git commit 
git push -f

перед git push -f надо проверить, что история верная с помощью команды git log

Если нужна помощь в этом - можешь дернуть Антона или меня

2024-02-26 21:14 UTC, merged