PRI 17: card
frontend-park-mail-ru/2024_1_TeaStealers pull request #5
Opened 2024-02-25 21:04 UTC by FZTOtt

Карточка объявления

PRI 17: card

2024-02-25 21:08 UTC, F4lkr4m requested changes

2024-02-25 21:08 UTC, F4lkr4m commented on public/components/card/card.html
> +                <div class="header">
card__header и так далее

2024-02-25 21:08 UTC, F4lkr4m commented on public/components/card/card.html
> +                <div class="save">
card__save-button?

2024-02-25 21:08 UTC, F4lkr4m commented on public/components/card/card.html
> +                    Кнопка для избранного
Сюда прям svg верстку вставить

2024-02-25 21:08 UTC, F4lkr4m commented on public/components/card/card.html
> +                <span class="fullprice">
card__fullprice?

2024-02-26 19:08 UTC, FZTOtt commented on public/components/card/card.html
> +                <div class="header">
fixed

2024-02-26 19:08 UTC, FZTOtt commented on public/components/card/card.html
> +                <div class="save">
fixed

2024-02-26 19:17 UTC, FZTOtt commented on public/components/card/card.html
> +                    Кнопка для избранного
вставил вместо div

2024-02-26 19:17 UTC, FZTOtt commented on public/components/card/card.html
> +                <span class="fullprice">
fixed

2024-02-26 20:04 UTC, closed without merging